// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB54-OF8T7slOslyakKtDRWjZypE6wf1gU',
    appId: '1:799385863021:web:944fbbb62ac7601dc69064',
    messagingSenderId: '799385863021',
    projectId: 'kezek-4af63',
    authDomain: 'kezek-4af63.firebaseapp.com',
    storageBucket: 'kezek-4af63.appspot.com',
    measurementId: 'G-WEN33MYY03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcBcmDgLMpov9N-eVtKwpWGFL1xCWh8s0',
    appId: '1:799385863021:android:9ed2576621f27d3cc69064',
    messagingSenderId: '799385863021',
    projectId: 'kezek-4af63',
    storageBucket: 'kezek-4af63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaoOWsBU_D1MFfjC30xPZyAbFuHxsmlZw',
    appId: '1:799385863021:ios:3905e20547adeed6c69064',
    messagingSenderId: '799385863021',
    projectId: 'kezek-4af63',
    storageBucket: 'kezek-4af63.appspot.com',
    iosBundleId: 'com.example.kazek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaoOWsBU_D1MFfjC30xPZyAbFuHxsmlZw',
    appId: '1:799385863021:ios:26ad91ac3f090afbc69064',
    messagingSenderId: '799385863021',
    projectId: 'kezek-4af63',
    storageBucket: 'kezek-4af63.appspot.com',
    iosBundleId: 'com.example.kazek.RunnerTests',
  );
}
